# Generated by Django 4.2.29 on 2026-04-19 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0006_puzzleimportbatch_puzzleimportpage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=30)),
                ('result', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('lost', 'Lost'), ('draw', 'Draw'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('score_delta', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to='positions.position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserPositionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_played_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('mastered', 'Mastered')], default='new', max_length=20)),
                ('mastery_score', models.IntegerField(default=0)),
                ('best_score', models.IntegerField(default=0)),
                ('last_score', models.IntegerField(default=0)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='positions.position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position_id'],
                'unique_together': {('user', 'position')},
            },
        ),
    ]
