# Generated by Django 4.2.29 on 2026-04-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceattempt',
            name='completed_normally',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='completion_reason',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='expected_line',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='matched_prefix_plies',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='played_line',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='target_depth_plies',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='userpositionstate',
            name='best_matched_prefix_plies',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpositionstate',
            name='last_matched_prefix_plies',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpositionstate',
            name='solved_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
