# Generated by Django 4.2.29 on 2026-04-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_practiceattempt_completed_normally_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpositionstate',
            name='current_perfect_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpositionstate',
            name='needs_homework',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpositionstate',
            name='perfect_record',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpositionstate',
            name='recent_accuracy_score',
            field=models.IntegerField(default=0),
        ),
    ]
