# Generated by Django 4.2.29 on 2026-03-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
