# Generated by Django 4.2.29 on 2026-03-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_position_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
