# Generated by Django 4.2.29 on 2026-03-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_position_source_maxlen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('opponent', models.CharField(max_length=100)),
                ('played_at', models.DateTimeField()),
                ('final_fen', models.TextField()),
                ('user_color', models.CharField(max_length=5)),
                ('winner', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['-played_at', '-id'],
            },
        ),
    ]
