# Generated by Django 4.2.29 on 2026-03-21 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0004_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
