# Generated by Django 4.2.29 on 2026-04-19 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('positions', '0005_alter_position_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready for review'), ('failed', 'Processing failed'), ('imported', 'Imported')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puzzle_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PuzzleImportPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_upload_path', models.TextField()),
                ('source_digest', models.CharField(blank=True, max_length=40)),
                ('normalized_image_path', models.TextField(blank=True)),
                ('overlay_image_path', models.TextField(blank=True)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('ocr_engine', models.CharField(blank=True, max_length=50)),
                ('ocr_theme_title', models.CharField(blank=True, max_length=200)),
                ('ocr_set_name', models.CharField(blank=True, max_length=20)),
                ('stage', models.PositiveIntegerField(blank=True, null=True)),
                ('theme_title', models.CharField(blank=True, max_length=200)),
                ('set_name', models.CharField(blank=True, max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='positions.puzzleimportbatch')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
